---
# Do not change this (Only for internal use)!
config-version: 1.1

# If this is set to true, dropped items will only be allowed when the player has
# permission "nodrops.bypass".
enable-permission: false

# Set this to true if you want to use the blacklisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# dropped items will be enabled for all worlds.
enable-world-blacklist: false
# If enable-world-blacklist is set to true, dropped items will be enabled for all worlds,
# except the worlds mentioned here.
blacklisted-worlds:
  - "blacklistedworld1"
  - "blacklistedworld2"

# Set this to true if you want to use the whitelisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# dropped items will be disabled for all worlds.
enable-world-whitelist: false
# If enable-world-whitelist is set to true, dropped items will be disabled for all worlds,
# except the worlds mentioned here.
whitelisted-worlds:
  - "whitelistedworld1"
  - "whitelistecworld2"

# If this is set to true, players who try to drop items will be sent a message telling them they cannot do so.
enable-message: true
# Message used when canceling a player dropping an item.
# Use "&" to color the message.
message: "&cYou can't drop your items here"

# If this is set to true, all items can't be dropped.
enable-all-items: false
# List of items that can't be dropped.
# If the item has meta, you can use the format "id:meta".
items:
  - "oak_log"
  - "diamond_ore"
  - "apple"
  - "diamond_pickaxe"
  - "oak_sapling"
...
